# Generated by Django 5.2 on 2025-05-08 00:57

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(11, 'O CPF do cliente é inválido!')])),
                ('login', models.CharField(max_length=15, unique=True)),
                ('senha', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(8, 'O Senha do cliente  é inválida!')])),
                ('guid', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
            ],
        ),
    ]
