# Generated by Django 5.2 on 2025-05-08 01:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(19, 'O CPF do cliente é inválido!')])),
                ('nomeComercial', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=15, unique=True)),
                ('senha', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(8, 'O Senha do cliente  é inválida!')])),
                ('guid', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
                ('categoria', models.CharField()),
                ('guid', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loja.vendedor')),
            ],
        ),
    ]
